### ISSUE TITLE
base.js:20 Uncaught TypeError

### ISSUE THREAD

**Issue by Kokiro** [ianc1/BaseCSS#2]
Hi I am getting this error:

base.js:20 Uncaught TypeError: target.parentNode.matches is not a function at HTMLDocument.dropdown (base.js:20)

BR,
Kokiro

**Comment by ianc1** [comment]
Hi Kokiro,

Thanks for reporting the issue. I've recreated the issue when clicking on the very bottom of a page where the body element doesn't fill the full height. I've fixed it and published a bugfix release, version 1.1.1.

Thanks,
Ian.
